import Nav from '@/components/Nav'
import Providers from '@/lib/utils/Providers/Provider.client'
import SVGIMG from '@/public/github.svg'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo App with Next.js and Prisma',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} bg-slate-800 text-slate-100 min-h-screen`}
      >
        <header className='flex justify-between items-center p-4'>
          <h1 className='text-2xl text-center'>Next Todos</h1>
          <Nav />
        </header>
        <Providers>{children}</Providers>
        <footer
          className='w-full  p-2 border-t
        absolute bottom-0'
        >
          <div className='flex flex-col items-center'>
            <Image src={SVGIMG} alt='github' width={40} />
            <span>Github: yigithancolak</span>
          </div>
        </footer>
      </body>
    </html>
  )
}
